#!/bin/bash
DOCKERFILE=Dockerfile

echo "Building $CACHE_TAG using build hook!"

if [[ $CACHE_TAG == *"python3"* ]]; then
    DOCKERFILE=Dockerfile-python3
fi

echo "Using $DOCKERFILE for build"

docker build \
        --build-arg SERVERLESS_VERSION=1.25.0 \
        --build-arg YARN_VERSION=1.3.2 \
        -f $DOCKERFILE \
        -t $IMAGE_NAME .
